Repository Nytely-Official/quickbooks-api, pull requests merged in 2025-02, with the labels that each got.

#1 Added the ability to revoke a Token once generated; Update the Exampl…
  README.md
  __tests__/auth-provider.test.ts
  example-usage.ts
  package.json
  src/packages/auth/auth-provider.ts
  src/types/enums/api-urls.ts
  src/types/enums/endpoints.ts
Labels: enhancement

#2 Add secure token serialization and validation
  README.md
  __tests__/auth-provider.test.ts
  example-usage.ts
  src/packages/auth/auth-provider.ts
  src/types/enums/api-urls.ts
  src/types/enums/endpoints.ts
Labels: enhancement

#4 Merge Develop into Production (Main)
  .github/workflows/publish.yml
  README.md
  __tests__/auth-provider.test.ts
  example-usage.ts
  package.json
  src/packages/auth/auth-provider.ts
  src/types/enums/api-urls.ts
  src/types/enums/endpoints.ts
Labels: enhancement

#5 Fixed Issues with the Publish Workflow
  .github/workflows/publish.yml
  CHANGELOG.md
  package.json
Labels: bug

#7 Added a prettier config file to set standards for the project; update…
  .prettierrc
  README.md
Labels: enhancement

#8 Enhanced the Invoice API
  README.md
  __tests__/__mocks__/invoice-data.ts
  __tests__/invoices.test.ts
  example-usage.ts
  src/app.ts
  src/packages/api/api-client.ts
  src/packages/api/invoices/invoice-api.ts
  src/packages/api/invoices/services/get-all-invoices.ts
  src/packages/api/invoices/services/get-invoice-by-id.ts
  src/packages/api/invoices/services/get-invoices-by-due-date.ts
  src/packages/api/invoices/services/get-invoices-for-date-range.ts
  src/packages/api/invoices/services/get-updated-invoices.ts
  src/packages/api/invoices/services/raw-invoice-query.ts
  src/packages/api/query-builder.ts
  src/packages/auth/auth-provider.ts
  src/types/enums/api-urls.ts
  src/types/enums/auth-scopes.ts
  src/types/enums/endpoints.ts
  src/types/enums/environment.ts
  src/types/enums/grant-type.ts
  src/types/enums/query.ts
  src/types/enums/token-type.ts
  src/types/interfaces/invoice.ts
  src/types/interfaces/query-response.ts
  src/types/interfaces/token-response.ts
  src/types/interfaces/token.ts
  src/types/interfaces/user-auth-response.ts
  src/types/types.ts
  src/types/types/deep-keys.ts
  tsconfig.json
Labels: enhancement

#9 Added live testing on Pull Requests
  .github/workflows/live-api-test.yml
  __tests__/live-test.ts
  package.json
Labels: enhancement

#11 Fixed issues with live tests
  .github/workflows/ci.yml
  .github/workflows/live-api-test.yml
  __live-tests__/auth-provider.test.ts
  __live-tests__/invoice-api.test.ts
  package.json
Labels: bug

#13 Updated the CI to include live tests
  .github/workflows/ci.yml
  .github/workflows/live-api-test.yml
  __tests__/live-test.ts
Labels: bug

#14 PRODUCTION MERGE - V0.1.2
  .github/workflows/ci.yml
  .prettierrc
  CHANGELOG.md
  README.md
  __live-tests__/auth-provider.test.ts
  __live-tests__/invoice-api.test.ts
  __tests__/__mocks__/invoice-data.ts
  __tests__/invoices.test.ts
  example-usage.ts
  package.json
  src/app.ts
  src/packages/api/api-client.ts
  src/packages/api/invoices/invoice-api.ts
  src/packages/api/invoices/services/get-all-invoices.ts
  src/packages/api/invoices/services/get-invoice-by-id.ts
  src/packages/api/invoices/services/get-invoices-by-due-date.ts
  src/packages/api/invoices/services/get-invoices-for-date-range.ts
  src/packages/api/invoices/services/get-updated-invoices.ts
  src/packages/api/invoices/services/raw-invoice-query.ts
  src/packages/api/query-builder.ts
  src/packages/auth/auth-provider.ts
  src/types/enums/api-urls.ts
  src/types/enums/auth-scopes.ts
  src/types/enums/endpoints.ts
  src/types/enums/environment.ts
  src/types/enums/grant-type.ts
  src/types/enums/query.ts
  src/types/enums/token-type.ts
  src/types/interfaces/invoice.ts
  src/types/interfaces/query-response.ts
  src/types/interfaces/token-response.ts
  src/types/interfaces/token.ts
  src/types/interfaces/user-auth-response.ts
  src/types/types.ts
  src/types/types/deep-keys.ts
  tsconfig.json
Labels: enhancement

#15 New search options system
  CHANGELOG.md
  README.md
  __live-tests__/invoice-api.test.ts
  example-usage.ts
  package.json
  src/packages/api/invoices/services/get-all-invoices.ts
  src/packages/api/invoices/services/get-invoice-by-id.ts
  src/packages/api/invoices/services/get-invoices-by-due-date.ts
  src/packages/api/invoices/services/get-invoices-for-date-range.ts
  src/packages/api/invoices/services/get-updated-invoices.ts
  src/packages/api/query-builder.ts
  src/packages/auth/auth-provider.ts
  src/types/interfaces/invoice-search-options.ts
  src/types/types.ts
Labels: enhancement

#19 Patched Refresh Token Issues
  CHANGELOG.md
  package.json
  src/packages/auth/auth-provider.ts
Labels: bug, enhancement

#20 Used New Refresh Tokens instead of existing token when refreshing access token
  CHANGELOG.md
  package.json
  src/packages/auth/auth-provider.ts
Labels: bug

#21 Release 0.4.0 - Pagination System Overhaul
  CHANGELOG.md
  README.md
  __live-tests__/estimate-api.test.ts
  __live-tests__/invoice-api.test.ts
  __tests__/estimates.test.ts
  __tests__/invoices.test.ts
  example-usage.ts
  package.json
  src/packages/api/api-client.ts
  src/packages/api/common/base-query-builder.ts
  src/packages/api/estimates/estimate-api.ts
  src/packages/api/estimates/services/get-all-estimates.ts
  src/packages/api/estimates/services/get-estimates-for-date-range.ts
  src/packages/api/estimates/services/get-updated-estimates.ts
  src/packages/api/estimates/services/raw-estimate-query.ts
  src/packages/api/invoices/invoice-api.ts
  src/packages/api/invoices/services/get-all-invoices.ts
  src/packages/api/invoices/services/get-invoices-by-due-date.ts
  src/packages/api/invoices/services/get-invoices-for-date-range.ts
  src/packages/api/invoices/services/get-updated-invoices.ts
  src/packages/api/invoices/services/raw-invoice-query.ts
  src/types/interfaces/search-options.ts
  src/types/interfaces/search-response.ts
  src/types/types.ts
  src/types/types/range.ts
Labels: enhancement

#22 feat(auth): implement event emitter for token refresh/revoke events
  CHANGELOG.md
  README.md
  __live-tests__/auth-provider.test.ts
  package.json
  src/packages/auth/auth-provider.ts
Labels: enhancement

#26 PROD RELEASE - PATCH AND AUTO REFRESH TOGGLE
  CHANGELOG.md
  __tests__/auth-provider.test.ts
  package.json
  src/packages/auth/auth-provider.ts
Labels: enhancement

#27 feat: Add Payment API and related types
  __live-tests__/payment-api.test.ts
  __tests__/__mocks__/payment-data.ts
  __tests__/helpers.ts
  __tests__/payments.test.ts
  src/packages/api/api-client.ts
  src/packages/api/payment/payment-api.ts
  src/packages/api/payment/payment-query-builder.ts
  src/packages/api/payment/services/get-all-payments.ts
  src/packages/api/payment/services/get-payment-by-due-date.ts
  src/packages/api/payment/services/get-payment-by-id.ts
  src/packages/api/payment/services/get-payments-for-date-range.ts
  src/packages/api/payment/services/get-updated-payments.ts
  src/packages/api/payment/services/raw-payment-query.ts
  src/types/interfaces/payment.ts
  src/types/interfaces/query-response.ts
  src/types/types.ts
Labels: enhancement

#33 feat: Add Credit Memo and Preference APIs, and enhance testing
  __live-tests__/credit-memo-api.test.ts
  __live-tests__/payment-api.test.ts
  __live-tests__/preference-api.test.ts
  __tests__/__mocks__/credit-memo-data.ts
  __tests__/__mocks__/preference-data.ts
  __tests__/credit-memo.test.ts
  __tests__/helpers.ts
  __tests__/preference.test.ts
  package.json
  src/packages/api/api-client.ts
  src/packages/api/credit-memo/credit-memo-api.ts
  src/packages/api/credit-memo/credit-memo-query-builder.ts
  src/packages/api/credit-memo/services/get-all-credit-memos.ts
  src/packages/api/credit-memo/services/get-credit-memo-by-id.ts
  src/packages/api/credit-memo/services/get-credit-memos-for-date-range.ts
  src/packages/api/credit-memo/services/get-updated-credit-memos.ts
  src/packages/api/credit-memo/services/raw-credit-memo-query.ts
  src/packages/api/preferences/preference-api.ts
  src/packages/api/preferences/preference-query-builder.ts
  src/packages/api/preferences/services/get-preferences.ts
  src/packages/api/preferences/services/raw-preference-query.ts
  src/types/interfaces/credit-memo.ts
  src/types/interfaces/preferences.ts
  src/types/interfaces/query-response.ts
  src/types/types.ts
Labels: enhancement

#34 feat: implement Account API with complete test suite
  __live-tests__/account-api.test.ts
  __tests__/__mocks__/account-data.ts
  __tests__/account.test.ts
  __tests__/auth-provider.test.ts
  __tests__/helpers.ts
  src/packages/api/account/account-api.ts
  src/packages/api/account/account-query-builder.ts
  src/packages/api/account/services/get-account-by-id.ts
  src/packages/api/account/services/get-accounts-created-for-date-range.ts
  src/packages/api/account/services/get-accounts-for-date-range.ts
  src/packages/api/account/services/get-all-accounts.ts
  src/packages/api/account/services/get-updated-accounts.ts
  src/packages/api/account/services/raw-account-query.ts
  src/packages/api/api-client.ts
  src/packages/auth/auth-provider.ts
  src/types/enums/query.ts
  src/types/interfaces/account.ts
  src/types/interfaces/query-response.ts
  src/types/types.ts
Labels: enhancement
